seed: 32
data:
  train: ./data/TinyStoriesV2-GPT4-train.npy
  valid: ./data/TinyStoriesV2-GPT4-valid.npy
  dtype: uint16
model:
  vocab_size: 10048
  context_length: 256
  d_model: 512
  num_layers: 8
  num_heads: 16
  d_ff: 1408
  rope_theta: 1e4
  device: cuda
optimizer:
  type: muon
  muon_lr: 0.01167
  muon_momentum: 0.95
  lr: 0.0044
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 0.1
train:
  batch_size: 32
  steps: 20
  lr_scheduler: wsd
  lr_max: 0.0044
  lr_min: 1e-6
  t_w: 2
  t_c: 18
  grad_clip: 1.0
  accum_steps: 1
  checkpoint: false
  log_interval: 1
